name: Image Build 

on:
  push:
    branches:
    - main

jobs:
  image-build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      id-token: none

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2

      - name: Registry Auth
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4.0.1
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=sha

      - name: build+push
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v3.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Sign the images
        run: |
          cosign sign ${{ steps.metadata.outputs.tags }}
        env:
          COSIGN_EXPERIMENTAL: 1
