name: PR

on:
  pull_request:
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: |
          echo $RANDOM > test.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply new files
