name: PR

on:
  pull_request:
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vars
        run: |
          echo FORK=$(echo ${{ toJson(github) }} | jq '.event.pull_request.head.repo.full_name') >> $GITHUB_ENV
      - run: |
          echo $FORK
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo "something" > test.yaml
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Updating files"
