name: PR

on:
  pull_request:
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vars
        env:
          JSON: ${{ toJSON(github) }}
        run: |
          echo "FORK=$(echo $JSON | jq -r '.event.pull_request.head.repo.full_name')" >> $GITHUB_ENV
          echo "BRANCH=$(echo $JSON | jq -r '.event.pull_request.head.ref')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.FORK }}
          ref: ${{ env.BRANCH }}
      - run: |
          echo "something" > test.yaml
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "Updating files"
          git push
