name: PR

on:
  pull_request:
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo $GITHUB_REPOSITORY
      - run: |
          cat test.yaml
      - run: |
          echo ${{ steps.PR.outputs.number }}
      - run: |
          echo "something" > test.yaml
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Updating files"
