name: PR

on:
  pull_request:
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo $GITHUB_REPOSITORY
      - uses: 8BitJonny/gh-get-current-pr@2.1.2
        id: PR
        with:
          # Authetication token to access GitHub APIs. (Can be omitted by default.)
          github-token: ${{ github.token }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          sha: ${{ github.event.pull_request.head.sha }}
      - run: |
          cat test.yaml
      - run: |
          echo $RANDOM > test.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply new files
